python/controle/controle_visitantes/urls.py
from django.contrib import admin
from django.urls import path
from dashboard.views import index
from visitantes.views import registrar_visitante, informacoes_visitante, finalizar_visita

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('registrar-visitante/', registrar_visitante, name="registrar_visitante"),
    path(
        'informacoes-visitante/<int:id>/', 
        informacoes_visitante, 
        name="informacoes_visitante"
    ),
    path(
        'informacoes-visitante/<int:id>/finalizar-visita', 
        finalizar_visita, 
        name="finalizar_visita"
    )
]

python/controle/visitantes/forms.py
from django import forms
from visitantes.models import Visitante

class VisitanteForm(forms.ModelForm):
    class Meta:
        model = Visitante
        fields = (
            "nome_completo",
            "cpf",
            "data_nascimento",
            "numero_casa",
            "placa_veiculo",
        )

        error_messages = {
            "nome_completo":{
                "required": "O nome completo é obrigatório"
            },
            "cpf": {
                "required": "O CPF é um campo obrigatório"
            },
            "data_nascimento":{
                "required": "A data é obrigatória",
                "invalid": "A data precisa ter o formato DD/MM/AAAA"
            },
            "numero_casa": {
                "required": "O número da casa é um campo obrigatório"
            },
        }
class AutorizaVisitanteForm(forms.ModelForm):
    morador_responsavel = forms.CharField(required=True)
    class Meta:
        model = Visitante
        fields = [
            "morador_responsavel"
        ]
        error_messages = {
            "morador_responsavel": {
                "required": "Informe o morador responsável"
            }
        }
        

python/controle/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Controle de Visitantes | Django Framework</title>
        
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">    
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body id="page-top">
        <div id="wrapper">
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                    <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-user-shield"></i>
                    </div>
                    
                    <div class="sidebar-brand-text">Controle de Visitantes</div>
                </a>
                
                <hr class="sidebar-divider my-0">
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">
                        <i class="fas fa-home"></i>
                        <span>Home</span>
                    </a>
                </li>
                
                <hr class="sidebar-divider">
            </ul>

            <div id="content-wrapper" class="d-flex flex-column">
                <div id="content">
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                        
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown no-arrow">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="mr-2 d-none d-lg-inline text-gray-800 small">
                                        <i class="fas fa-cog"></i>
                                    </span>
                                </a>
                                
                                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Sair
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </nav>

                    {% block conteudo %} {% endblock conteudo %}

                    <footer class="sticky-footer bg-white">
                        <div class="container my-auto">
                            <div class="copyright text-center my-auto">
                                <span>Copyright © Django framework</span>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>

            <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="ModalLabel">Você realmente deseja sair?</h5>
                            
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true"></span>
                            </button>
                        </div>
                        
                        <div class="modal-body">Selecione "sair" se realmente deseja sair</div>
                        
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                            <a class="btn btn-primary" href="#">Sair</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
        <script src="{% static 'js/sb-admin-2.min.js'%}"></script>
    </body>
</html>

python/controle/templates/index.html
{% extends "base.html" %}

{% block conteudo %}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>

        <a href="{% url 'registrar_visitante' %}" class="btn btn-primary btn-icon-spit btn-sm">
            <span class="text">Registrar visitante</span>

            <span class="icon text-white-50">
                <i class="fas fa-user-plus"></i>
            </span>
        </a> 
    </div>

    {% if messages %}
        {% for mensagem in messages %}
            <div class="alert alert-success" role="alert">
                {{ mensagem }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Visitantes aguardando autorização</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                        </div>
                        
                        <div class="col-auto">
                            <i class="fas fa-user-lock fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Visitantes no condomínio</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                        </div>
                        
                        <div class="col-auto">
                            <i class="fas fa-user-clock fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Visitas finalizadas</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user-check fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Visitantes registrados no mês atual</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-sm-flex align-items-center justify-content-between mb-4">
            <h6 class="m-0 font-weight-bold text-primary">Visitantes recentes</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <th>Nome completo</th>
                        <th>CPF</th>
                        <th>Horário de chegada</th>
                        <th>Horário da autorização</th>
                        <th>Autorizado por</th>
                        <th>Mais informações</th>
                    </thead>
                    <tbody>
                        {% for variavel in todos_visitantes %}
                        <tr>
                            <td>{{ variavel.nome_completo }}</td>
                            <td>{{ variavel.cpf }}</td>
                            <td>{{ variavel.horario_chegada }}</td>
                            <td>{{ variavel.get_horario_autorizacao }}</td>
                            <td>{{ variavel.get_morador_responsavel }}</td>
                            <td>

                                <a href="{% url 'informacoes_visitante' id=variavel.id %}" >
                                    Ver informações
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock conteudo %}

python/controle/templates/informacoes_visitante.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block conteudo %}
<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>

        <div>
            <a href="#" class="btn btn-success btn-icon-split btn-sm" data-toggle="modal" data-target="#modal1">
                <span class="text">Autorizar Entrada</span>

                <span class="icon text-white-50">
                    <i class="fas fa-user-check"></i>
                </span>
            </a>

            <a href="#" class="btn btn-warning btn-icon-split btn-sm" data-toggle="modal" data-target="#modal2">
                <span class="text">Finalizar Visita</span>

                <span class="icon text-white-50">
                    <i class="fas fa-door-open"></i>
                </span>
            </a>            
        </div>
    </div>
    
    <div class="card shadow mb-4">        
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Informações gerais
            </h4>
        
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Horário de chegada</label>
                        <input type="text" class="form-control" value="{{visitante.horario_chegada}}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Número da casa a ser visitada</label>
                        <input type="text" class="form-control" value="{{visitante.numero_casa}}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>Horário de autorização de entrada</label>
                        <input type="text" class="form-control" value="{{visitante.get_horario_autorizacao}}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Entrada autorizada por</label>
                        <input type="text" class="form-control" value="{{visitante.get_morador_responsavel}}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Horário de saída</label>
                        <input type="text" class="form-control" value="{{visitante.get_horario_saida}}" disabled>
                    </div>
                </div>
            </form>
        
            <h4 class="mb-3 mt-4 text-primary">
                Informações pessoais
            </h4>
            
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Nome completo</label>
                        <input type="text" class="form-control" value="{{visitante.nome_completo}}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>CPF</label>
                        <input type="text" class="form-control" value="{{visitante.cpf}}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Data de nascimento</label>
                        <input type="text" class="form-control" value="{{visitante.data_nascimento}}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Placa do veículo</label>
                        <input type="text" class="form-control" value="{{visitante.get_placa_veiculo}}" disabled>
                    </div>
                </div>
            </form>
                    
            <p class="mr-2 mt-3 mb-4 text-right">
                <small>
                    Visitante registrado em 15/05/2018 por {{visitante.registrado_por}}
                </small>
            </p>
        
            <div class="mr-1 text-right">
                <a href="#" class="btn btn-secondary text-white" type="button">
                    <span class="text">Voltar</span>
                </a>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Autorizar entrada de visitante</h5>
                    
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                
                <div class="modal-body">
                    <form method="post">
                        {% csrf_token %}
    
                        <div class="form-group">
                            <label for="id_morador_responsavel" class="col-form-label">Nome do morador responsável por autorizar a entrada do visitante:</label>
                            {% render_field form.morador_responsavel placeholder="Nome do morador responsável por autorizar a entrada do visitante" class="form-control" %}
                        </div>
                            
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-primary">Autorizar entrada</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Finalizar visita</h5>
                        
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                
                <div class="modal-body">
                    <div class="modal-body">
                        <h5 class="mb-3">
                            Realmente deseja encerrar a visita?
                        </h5>
    
                        <form method="post" action="{% url 'finalizar_visita' id=visitante.id %}">
                            {% csrf_token %}
    
                            <input hidden>
    
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary">Finalizar visita</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>
{% endblock %}

python/controle/templates/registrar_visitante.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block conteudo %}
<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Formulário para registro de novo visitante
            </h4>

            <p class="mb-5 ml=1">
              <small>
                (*) Campo obrigatório
              </small>
            </p>
            
            {% if form.errors %}
              {% for field in form %}
                {% if field.errors %}
                  {% for erro in field.errors %}
                    <div class = "alert alert-warning" role="alert">
                      {{ erro }}
                    </div>
                  {% endfor %}
                {% endif %}  
              {% endfor %}
            {% endif %}

            <form method="post">
                <div class="form-row">
                  {% csrf_token %}
              
                  {% for field in form %}
                    <div class="form-group col-md-12">
                      <label>{{ field.label }}</label>
                      {% if field.field.required %} * {% endif %}
                      {% render_field field placeholder=field.label class="form-control" %}
                    </div>
                  {% endfor %}
                </div>

                <div class="text-right">
                  <button class="btn btn-primary" type="submit">
                    <span class="text">Registrar Visitante</span>
                  </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock conteudo %}